/**
 * @jest-environment jsdom
 */
import React from 'react';
import { render } from '@testing-library/react';
import { CreationSummary } from '../src/components/CreationSummary.jsx';

const baseRows = [
  { key: 'image', step: 0, label: 'Image', values: ['nginx:1.27-alpine'] },
  { key: 'name', step: 1, label: 'Name', values: ['(auto-generated by Docker)'], origin: 'Docker will assign a name' },
  { key: 'ports', step: 2, label: 'Ports', values: ['8080→80/tcp'], origin: 'assigned by CDD' },
  { key: 'env', step: 3, label: 'Env', values: ['(none)'] },
];

describe('CreationSummary', () => {
  test('renders all row labels', () => {
    const { getByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(getByText('Review and confirm')).toBeTruthy();
    expect(getByText('Image')).toBeTruthy();
    expect(getByText('Name')).toBeTruthy();
    expect(getByText('Ports')).toBeTruthy();
    expect(getByText('Env')).toBeTruthy();
  });

  test('renders row values', () => {
    const { getByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(getByText('nginx:1.27-alpine')).toBeTruthy();
    expect(getByText('(auto-generated by Docker)')).toBeTruthy();
    expect(getByText('8080→80/tcp')).toBeTruthy();
  });

  test('renders origin text when present', () => {
    const { getByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(getByText(/\u2193 Docker will assign a name/)).toBeTruthy();
    expect(getByText(/\u2193 assigned by CDD/)).toBeTruthy();
  });

  test('does NOT render origin when absent', () => {
    const rows = [
      { key: 'image', step: 0, label: 'Image', values: ['nginx:1.27-alpine'] },
    ];
    const { queryByText } = render(
      <CreationSummary
        rows={rows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(queryByText(/\u2193/)).toBeNull();
  });

  test('renders warnings with correct color', () => {
    const warnings = [
      { kind: 'image-pull', level: 'info', text: 'Image will be pulled.' },
      { kind: 'port-taken', level: 'warn', text: 'Port 8080 is in use.' },
    ];
    const { getByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={warnings}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(getByText(/Image will be pulled/)).toBeTruthy();
    expect(getByText(/Port 8080 is in use/)).toBeTruthy();
  });

  test('does NOT render warnings when empty', () => {
    const { queryByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(queryByText('\u26A0')).toBeNull();
  });

  test('shows loading preview text when isLoadingPreview is true', () => {
    const { getByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={true}
      />
    );
    expect(getByText(/Checking image/)).toBeTruthy();
  });

  test('hides loading preview text when isLoadingPreview is false', () => {
    const { queryByText } = render(
      <CreationSummary
        rows={baseRows}
        warnings={[]}
        focusedRow={0}
        isLoadingPreview={false}
      />
    );
    expect(queryByText(/Checking image/)).toBeNull();
  });
});
