let buildCreationSummary;
let buildCreationWarnings;
let detectPortConflicts;

beforeAll(async () => {
  const mod = await import('../src/helpers/creationSummary.js');
  buildCreationSummary = mod.buildCreationSummary;
  buildCreationWarnings = mod.buildCreationWarnings;
  detectPortConflicts = mod.detectPortConflicts;
});

import { IMAGE_PROFILES } from '../src/helpers/constants.js';

const profiles = {
  postgres: {
    requiredEnv: ['POSTGRES_PASSWORD'],
    defaultPort: '5432',
    defaultTag: '17-alpine',
    suggestedEnv: ['POSTGRES_PASSWORD=secret', 'POSTGRES_DB=app'],
  },
  nginx: {
    requiredEnv: [],
    defaultPort: '80',
    defaultTag: '1.27-alpine',
    suggestedEnv: [],
  },
};

describe('buildCreationSummary', () => {
  test('image with implicit tag shows resolved tag and origin', () => {
    const rows = buildCreationSummary(
      {
        imageName: 'postgres:17-alpine',
        containerName: '',
        portInput: '',
        envInput: '',
      },
      {
        rawImageInput: 'postgres',
        imageProfiles: profiles,
        previewedPorts: null,
      }
    );
    const imageRow = rows.find((r) => r.key === 'image');
    expect(imageRow.values[0]).toBe('postgres:17-alpine');
    expect(imageRow.origin).toBe('you typed "postgres"');
  });

  test('image with explicit tag shows no origin', () => {
    const rows = buildCreationSummary(
      {
        imageName: 'nginx:1.27-alpine',
        containerName: '',
        portInput: '',
        envInput: '',
      },
      {
        rawImageInput: 'nginx:1.27-alpine',
        imageProfiles: profiles,
        previewedPorts: null,
      }
    );
    const imageRow = rows.find((r) => r.key === 'image');
    expect(imageRow.origin).toBeUndefined();
  });

  test('empty container name shows auto-generated', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const nameRow = rows.find((r) => r.key === 'name');
    expect(nameRow.values[0]).toBe('(auto-generated by Docker)');
    expect(nameRow.origin).toBe('Docker will assign a name');
  });

  test('named container shows name without origin', () => {
    const rows = buildCreationSummary(
      {
        imageName: 'nginx',
        containerName: 'my-web',
        portInput: '',
        envInput: '',
      },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const nameRow = rows.find((r) => r.key === 'name');
    expect(nameRow.values[0]).toBe('my-web');
    expect(nameRow.origin).toBeUndefined();
  });

  test('user-provided ports show without origin', () => {
    const rows = buildCreationSummary(
      {
        imageName: 'nginx',
        containerName: '',
        portInput: '8080:80',
        envInput: '',
      },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toBe('8080:80');
    expect(portsRow.origin).toBeUndefined();
  });

  test('empty ports with preview shows auto-assigned ports', () => {
    const preview = [
      { hostPort: '5432', containerPort: '5432', protocol: 'tcp' },
    ];
    const rows = buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      {
        rawImageInput: 'postgres',
        imageProfiles: profiles,
        previewedPorts: preview,
      }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toContain('5432');
    expect(portsRow.origin).toBe('assigned by CDD');
  });

  test('a previewed port with no free host slot says so instead of printing null', () => {
    const preview = [
      { hostPort: null, containerPort: '5432', protocol: 'tcp' },
    ];
    const rows = buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      {
        rawImageInput: 'postgres',
        imageProfiles: profiles,
        previewedPorts: preview,
      }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toBe('(no free host port)→5432/tcp');
    expect(portsRow.values[0]).not.toContain('null');
  });

  test('empty ports without preview shows fallback message', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toContain('CDD will pick');
  });

  test('env vars show values, password masked', () => {
    const rows = buildCreationSummary(
      {
        imageName: 'postgres',
        containerName: '',
        portInput: '',
        envInput: 'POSTGRES_PASSWORD=secret,POSTGRES_DB=app',
      },
      {
        rawImageInput: 'postgres',
        imageProfiles: profiles,
        previewedPorts: null,
      }
    );
    const envRow = rows.find((r) => r.key === 'env');
    expect(envRow.values.some((v) => v.includes('POSTGRES_DB=app'))).toBe(true);
    expect(envRow.values.some((v) => v.includes('\u2022'))).toBe(true);
  });

  test('empty env shows (none)', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const envRow = rows.find((r) => r.key === 'env');
    expect(envRow.values[0]).toBe('(none)');
  });
});

describe('detectPortConflicts', () => {
  // The real getContainers() shape: published ports are "host:container".
  const containers = [
    { name: 'web', id: 'abc', ports: ['8080:80', '443:443'] },
    { name: 'db', id: 'def', ports: ['5432:5432'] },
  ];

  test('detects host port conflict', () => {
    const conflicts = detectPortConflicts('8080:80', containers);
    expect(conflicts).toHaveLength(1);
    expect(conflicts[0].hostPort).toBe('8080');
    expect(conflicts[0].takenBy).toBe('web');
  });

  test('ignores container port conflicts (only host matters)', () => {
    const conflicts = detectPortConflicts('9090:5432', containers);
    expect(conflicts).toHaveLength(0);
  });

  test('returns empty for empty input', () => {
    expect(detectPortConflicts('', containers)).toHaveLength(0);
    expect(detectPortConflicts('  ', containers)).toHaveLength(0);
  });

  test('detects multiple conflicts', () => {
    const conflicts = detectPortConflicts('8080:80,5432:5432', containers);
    expect(conflicts).toHaveLength(2);
  });

  // D22. An exposed-but-unpublished port is not a host port.
  test('ignores an exposed-but-unpublished private port', () => {
    const conflicts = detectPortConflicts('80:80', [
      { name: 'web', id: 'a', ports: ['80'] },
    ]);
    expect(conflicts).toEqual([]);
  });
});

describe('buildCreationWarnings', () => {
  test('image-pull warning when image is not local', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'postgres:17',
        containerName: '',
        portInput: '',
        envInput: '',
      },
      { containers: [], imageIsLocal: false, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(true);
  });

  test('no image-pull warning when image is local', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'postgres:17',
        containerName: '',
        portInput: '',
        envInput: '',
      },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(false);
  });

  test('no image-pull warning when imageIsLocal is null', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'postgres:17',
        containerName: '',
        portInput: '',
        envInput: '',
      },
      { containers: [], imageIsLocal: null, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(false);
  });

  test('port-taken warning when host port is in use', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'nginx',
        containerName: '',
        portInput: '8080:80',
        envInput: '',
      },
      {
        containers: [{ name: 'web', ports: ['8080:80'] }],
        imageIsLocal: true,
        imageProfiles: profiles,
      }
    );
    expect(warnings.some((w) => w.kind === 'port-taken')).toBe(true);
  });

  test('name-taken warning when container name exists', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'nginx', containerName: 'web', portInput: '', envInput: '' },
      {
        containers: [{ name: 'web', ports: [] }],
        imageIsLocal: true,
        imageProfiles: profiles,
      }
    );
    expect(warnings.some((w) => w.kind === 'name-taken')).toBe(true);
  });

  test('missing-env warning for required env vars', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'missing-env')).toBe(true);
  });

  test('no missing-env when required vars are present', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'postgres',
        containerName: '',
        portInput: '',
        envInput: 'POSTGRES_PASSWORD=secret',
      },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'missing-env')).toBe(false);
  });

  test('secret-plain warning for PASSWORD in env', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'nginx',
        containerName: '',
        portInput: '',
        envInput: 'DB_PASSWORD=123456',
      },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'secret-plain')).toBe(true);
  });

  test('no secret-plain warning while the secret has no value yet', () => {
    // There is nothing in plain text to warn about; the empty-value warning
    // already says what is wrong, and saying both reads as a contradiction.
    const warnings = buildCreationWarnings(
      {
        imageName: 'nginx',
        containerName: '',
        portInput: '',
        envInput: 'DB_PASSWORD=,API_TOKEN=   ',
      },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'secret-plain')).toBe(false);
  });

  test('secret-plain still fires for the secret that has a value', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'nginx',
        containerName: '',
        portInput: '',
        envInput: 'DB_PASSWORD=,API_TOKEN=abc123',
      },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    const plain = warnings.filter((w) => w.kind === 'secret-plain');
    expect(plain).toHaveLength(1);
    expect(plain[0].text).toContain('API_TOKEN');
  });

  test('multiple warnings at once', () => {
    const warnings = buildCreationWarnings(
      {
        imageName: 'postgres',
        containerName: 'db',
        portInput: '5432:5432',
        envInput: 'SECRET_KEY=abc',
      },
      {
        containers: [{ name: 'db', ports: ['5432:5432'] }],
        imageIsLocal: false,
        imageProfiles: profiles,
      }
    );
    const kinds = warnings.map((w) => w.kind);
    expect(kinds).toContain('image-pull');
    expect(kinds).toContain('port-taken');
    expect(kinds).toContain('name-taken');
    expect(kinds).toContain('secret-plain');
  });
});

describe('buildCreationSummary — what CDD changed (TASK-8)', () => {
  const values = {
    imageName: 'postgres:17-alpine',
    containerName: 'mi-basedatos-2',
    portInput: '5432:5432',
    envInput: 'POSTGRES_PASSWORD=secret',
  };
  const build = (changedFields) =>
    buildCreationSummary(values, {
      rawImageInput: 'postgres:17-alpine',
      imageProfiles: profiles,
      previewedPorts: null,
      changedFields,
    });

  test('marks the rows the fix touched', () => {
    const changed = build(['envInput', 'containerName'])
      .filter((r) => r.changed)
      .map((r) => r.key);
    expect(changed).toEqual(['name', 'env']);
  });

  test('leaves the untouched rows alone', () => {
    const rows = build(['envInput']);
    expect(rows.find((r) => r.key === 'image').changed).toBeUndefined();
    expect(rows.find((r) => r.key === 'ports').changed).toBeUndefined();
  });

  test('no changedFields means no marking', () => {
    expect(build([]).some((r) => r.changed)).toBe(false);
    expect(build(undefined).some((r) => r.changed)).toBe(false);
  });

  test('an unknown field name marks nothing rather than crashing', () => {
    expect(build(['nonsense']).some((r) => r.changed)).toBe(false);
  });

  test('every wizard field maps to some row', () => {
    const keys = build([
      'imageName',
      'containerName',
      'portInput',
      'envInput',
    ]).map((r) => r.key);
    expect(keys).toEqual(
      expect.arrayContaining(['image', 'name', 'ports', 'env'])
    );
  });

  test('marking does not change the values shown', () => {
    const plain = build([]).find((r) => r.key === 'env');
    const flagged = build(['envInput']).find((r) => r.key === 'env');
    expect(flagged.values).toEqual(plain.values);
  });
});

describe('a required variable that is set but empty', () => {
  // The state TASK-8's password fix lands in on purpose: CDD cannot invent a
  // password, so the review has to say the container will fail without one.
  const warningsFor = (envInput, image = 'postgres') =>
    buildCreationWarnings(
      { imageName: image, containerName: '', portInput: '', envInput },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );

  test('the review warns when a required var has no value', () => {
    const warning = warningsFor('POSTGRES_PASSWORD=').find(
      (w) => w.kind === 'missing-env'
    );
    expect(warning).toBeDefined();
    expect(warning.text).toContain('POSTGRES_PASSWORD');
    expect(warning.text).toMatch(/empty/i);
  });

  test('and says the container will fail without it', () => {
    const warning = warningsFor('POSTGRES_PASSWORD=').find(
      (w) => w.kind === 'missing-env'
    );
    expect(warning.text).toMatch(/fail/i);
  });

  test('a filled-in value produces no such warning', () => {
    const kinds = warningsFor('POSTGRES_PASSWORD=hunter2').map((w) => w.kind);
    expect(kinds).not.toContain('missing-env');
  });

  test('an absent var keeps the "missing" wording, not "empty"', () => {
    const warning = warningsFor('POSTGRES_USER=app').find(
      (w) => w.kind === 'missing-env'
    );
    expect(warning.text).toContain('Missing required env vars');
    expect(warning.text).not.toContain('empty');
  });

  test('a var absent entirely is still reported once, not twice', () => {
    const missing = warningsFor('POSTGRES_USER=app').filter(
      (w) => w.kind === 'missing-env'
    );
    expect(missing).toHaveLength(1);
  });

  test('two empty vars are named together and read in the plural', () => {
    // mssql requires two, so it exercises the plural branch.
    const warning = buildCreationWarnings(
      {
        imageName: 'mssql',
        containerName: '',
        portInput: '',
        envInput: 'ACCEPT_EULA=,SA_PASSWORD=',
      },
      { containers: [], imageIsLocal: true, imageProfiles: IMAGE_PROFILES }
    ).find((w) => w.kind === 'missing-env');
    expect(warning.text).toContain('ACCEPT_EULA');
    expect(warning.text).toContain('SA_PASSWORD');
    expect(warning.text).toMatch(/vars set but empty/);
  });

  test('a single empty var is worded in the singular', () => {
    const warning = warningsFor('POSTGRES_PASSWORD=').find(
      (w) => w.kind === 'missing-env'
    );
    expect(warning.text).toMatch(/var set but empty/);
    expect(warning.text).toContain('POSTGRES_PASSWORD');
  });

  test('a whitespace-only value counts as empty', () => {
    const warning = warningsFor('POSTGRES_PASSWORD=   ').find(
      (w) => w.kind === 'missing-env'
    );
    expect(warning).toBeDefined();
  });

  test('images with no required vars are unaffected', () => {
    const kinds = warningsFor('FOO=', 'nginx').map((w) => w.kind);
    expect(kinds).not.toContain('missing-env');
  });
});

describe('buildCreationSummary — empty secrets and recreations', () => {
  const envRow = (envInput) =>
    buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput },
      { rawImageInput: 'postgres', imageProfiles: profiles, previewedPorts: null }
    ).find((r) => r.key === 'env');

  const portsRow = (ctx) =>
    buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      {
        rawImageInput: 'postgres',
        imageProfiles: profiles,
        previewedPorts: [
          { hostPort: '5433', containerPort: '5432', protocol: 'tcp' },
        ],
        ...ctx,
      }
    ).find((r) => r.key === 'ports');

  test('an empty secret is shown as (empty), not as dots', () => {
    expect(envRow('POSTGRES_PASSWORD=').values).toEqual([
      'POSTGRES_PASSWORD=(empty)',
    ]);
  });

  test('a whitespace-only secret value counts as empty', () => {
    expect(envRow('POSTGRES_PASSWORD=   ').values).toEqual([
      'POSTGRES_PASSWORD=(empty)',
    ]);
  });

  test('a filled-in secret is still masked', () => {
    expect(envRow('POSTGRES_PASSWORD=hunter2').values).toEqual([
      'POSTGRES_PASSWORD=\u2022\u2022\u2022\u2022\u2022\u2022',
    ]);
  });

  test('a non-secret key with an empty value is left alone', () => {
    expect(envRow('POSTGRES_USER=').values).toEqual(['POSTGRES_USER=']);
  });

  test('a recreation says the original published no ports', () => {
    expect(portsRow({ recreating: true }).origin).toBe(
      'assigned by CDD \u2014 the original published no ports'
    );
  });

  test('a normal wizard keeps the plain origin', () => {
    expect(portsRow({}).origin).toBe('assigned by CDD');
    expect(portsRow({ recreating: false }).origin).toBe('assigned by CDD');
  });
});

describe('buildCreationSummary — values with escaped commas (V1)', () => {
  const envRow = (envInput) =>
    buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput },
      { rawImageInput: 'postgres', imageProfiles: profiles, previewedPorts: null }
    ).find((r) => r.key === 'env');

  test('a secret whose value carries a comma is masked in full', () => {
    // The review used to split on the comma and render "s3cr3t" in the clear.
    const row = envRow('POSTGRES_PASSWORD=hunter2\\,s3cr3t,POSTGRES_DB=app');
    expect(row.values).toEqual([
      'POSTGRES_PASSWORD=\u2022\u2022\u2022\u2022\u2022\u2022',
      'POSTGRES_DB=app',
    ]);
    expect(row.values.join('\n')).not.toContain('s3cr3t');
    expect(row.values.join('\n')).not.toContain('hunter2');
  });

  test('a non-secret value keeps its real comma in one line', () => {
    const row = envRow('KAFKA_LISTENERS=a\\,b');
    expect(row.values).toEqual(['KAFKA_LISTENERS=a,b']);
  });
});
