let buildCreationSummary;
let buildCreationWarnings;
let detectPortConflicts;

beforeAll(async () => {
  const mod = await import('../src/helpers/creationSummary.js');
  buildCreationSummary = mod.buildCreationSummary;
  buildCreationWarnings = mod.buildCreationWarnings;
  detectPortConflicts = mod.detectPortConflicts;
});

const profiles = {
  postgres: {
    requiredEnv: ['POSTGRES_PASSWORD'],
    defaultPort: '5432',
    defaultTag: '17-alpine',
    suggestedEnv: ['POSTGRES_PASSWORD=secret', 'POSTGRES_DB=app'],
  },
  nginx: {
    requiredEnv: [],
    defaultPort: '80',
    defaultTag: '1.27-alpine',
    suggestedEnv: [],
  },
};

describe('buildCreationSummary', () => {
  test('image with implicit tag shows resolved tag and origin', () => {
    const rows = buildCreationSummary(
      { imageName: 'postgres:17-alpine', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'postgres', imageProfiles: profiles, previewedPorts: null }
    );
    const imageRow = rows.find((r) => r.key === 'image');
    expect(imageRow.values[0]).toBe('postgres:17-alpine');
    expect(imageRow.origin).toBe('you typed "postgres"');
  });

  test('image with explicit tag shows no origin', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx:1.27-alpine', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx:1.27-alpine', imageProfiles: profiles, previewedPorts: null }
    );
    const imageRow = rows.find((r) => r.key === 'image');
    expect(imageRow.origin).toBeUndefined();
  });

  test('empty container name shows auto-generated', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const nameRow = rows.find((r) => r.key === 'name');
    expect(nameRow.values[0]).toBe('(auto-generated by Docker)');
    expect(nameRow.origin).toBe('Docker will assign a name');
  });

  test('named container shows name without origin', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: 'my-web', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const nameRow = rows.find((r) => r.key === 'name');
    expect(nameRow.values[0]).toBe('my-web');
    expect(nameRow.origin).toBeUndefined();
  });

  test('user-provided ports show without origin', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '8080:80', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toBe('8080:80');
    expect(portsRow.origin).toBeUndefined();
  });

  test('empty ports with preview shows auto-assigned ports', () => {
    const preview = [{ hostPort: '5432', containerPort: '5432', protocol: 'tcp' }];
    const rows = buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'postgres', imageProfiles: profiles, previewedPorts: preview }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toContain('5432');
    expect(portsRow.origin).toBe('assigned by CDD');
  });

  test('empty ports without preview shows fallback message', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const portsRow = rows.find((r) => r.key === 'ports');
    expect(portsRow.values[0]).toContain('CDD will pick');
  });

  test('env vars show values, password masked', () => {
    const rows = buildCreationSummary(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: 'POSTGRES_PASSWORD=secret,POSTGRES_DB=app' },
      { rawImageInput: 'postgres', imageProfiles: profiles, previewedPorts: null }
    );
    const envRow = rows.find((r) => r.key === 'env');
    expect(envRow.values.some((v) => v.includes('POSTGRES_DB=app'))).toBe(true);
    expect(envRow.values.some((v) => v.includes('\u2022'))).toBe(true);
  });

  test('empty env shows (none)', () => {
    const rows = buildCreationSummary(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: '' },
      { rawImageInput: 'nginx', imageProfiles: profiles, previewedPorts: null }
    );
    const envRow = rows.find((r) => r.key === 'env');
    expect(envRow.values[0]).toBe('(none)');
  });
});

describe('detectPortConflicts', () => {
  const containers = [
    { name: 'web', id: 'abc', ports: ['8080', '443'] },
    { name: 'db', id: 'def', ports: ['5432'] },
  ];

  test('detects host port conflict', () => {
    const conflicts = detectPortConflicts('8080:80', containers);
    expect(conflicts).toHaveLength(1);
    expect(conflicts[0].hostPort).toBe('8080');
    expect(conflicts[0].takenBy).toBe('web');
  });

  test('ignores container port conflicts (only host matters)', () => {
    const conflicts = detectPortConflicts('9090:5432', containers);
    expect(conflicts).toHaveLength(0);
  });

  test('returns empty for empty input', () => {
    expect(detectPortConflicts('', containers)).toHaveLength(0);
    expect(detectPortConflicts('  ', containers)).toHaveLength(0);
  });

  test('detects multiple conflicts', () => {
    const conflicts = detectPortConflicts('8080:80,5432:5432', containers);
    expect(conflicts).toHaveLength(2);
  });
});

describe('buildCreationWarnings', () => {
  test('image-pull warning when image is not local', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres:17', containerName: '', portInput: '', envInput: '' },
      { containers: [], imageIsLocal: false, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(true);
  });

  test('no image-pull warning when image is local', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres:17', containerName: '', portInput: '', envInput: '' },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(false);
  });

  test('no image-pull warning when imageIsLocal is null', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres:17', containerName: '', portInput: '', envInput: '' },
      { containers: [], imageIsLocal: null, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'image-pull')).toBe(false);
  });

  test('port-taken warning when host port is in use', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'nginx', containerName: '', portInput: '8080:80', envInput: '' },
      { containers: [{ name: 'web', ports: ['8080'] }], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'port-taken')).toBe(true);
  });

  test('name-taken warning when container name exists', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'nginx', containerName: 'web', portInput: '', envInput: '' },
      { containers: [{ name: 'web', ports: [] }], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'name-taken')).toBe(true);
  });

  test('missing-env warning for required env vars', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: '' },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'missing-env')).toBe(true);
  });

  test('no missing-env when required vars are present', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres', containerName: '', portInput: '', envInput: 'POSTGRES_PASSWORD=secret' },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'missing-env')).toBe(false);
  });

  test('secret-plain warning for PASSWORD in env', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'nginx', containerName: '', portInput: '', envInput: 'DB_PASSWORD=123456' },
      { containers: [], imageIsLocal: true, imageProfiles: profiles }
    );
    expect(warnings.some((w) => w.kind === 'secret-plain')).toBe(true);
  });

  test('multiple warnings at once', () => {
    const warnings = buildCreationWarnings(
      { imageName: 'postgres', containerName: 'db', portInput: '5432:5432', envInput: 'SECRET_KEY=abc' },
      { containers: [{ name: 'db', ports: ['5432'] }], imageIsLocal: false, imageProfiles: profiles }
    );
    const kinds = warnings.map((w) => w.kind);
    expect(kinds).toContain('image-pull');
    expect(kinds).toContain('port-taken');
    expect(kinds).toContain('name-taken');
    expect(kinds).toContain('secret-plain');
  });
});
