import { normalizeImageName } from './imageNameUtils.js';

/**
 * @typedef {Object} SummaryRow
 * @property {string} key     - 'image' | 'name' | 'ports' | 'env'
 * @property {number} step    - Step index to jump to when editing
 * @property {string} label   - Display label
 * @property {string[]} values - One or more value lines
 * @property {string} [origin] - Explanatory second line
 */

/**
 * @typedef {Object} Warning
 * @property {'image-pull'|'port-taken'|'name-taken'|'missing-env'|'secret-plain'} kind
 * @property {'info'|'warn'|'block'} level
 * @property {string} text
 */

/**
 * Builds the summary table from wizard values.
 * Pure: does not call Docker.
 *
 * @param {Object} values - { imageName, containerName, portInput, envInput }
 * @param {Object} ctx
 * @param {string} ctx.rawImageInput - What the user originally typed for the image
 * @param {Object} ctx.imageProfiles - Profile map
 * @param {Array} [ctx.previewedPorts] - Auto-assigned ports from preview, or null
 * @returns {SummaryRow[]}
 */
export function buildCreationSummary(values, ctx) {
  const { imageName, containerName, portInput, envInput } = values;
  const { rawImageInput, imageProfiles, previewedPorts } = ctx;

  const rows = [];

  // — Image —
  const baseName = normalizeImageName(imageName);
  const imageValues = [imageName];
  let imageOrigin;
  if (rawImageInput && rawImageInput !== imageName) {
    imageOrigin = `you typed "${rawImageInput}"`;
  }
  rows.push({ key: 'image', step: 0, label: 'Image', values: imageValues, origin: imageOrigin });

  // — Name —
  const nameDisplay = containerName.trim() || '(auto-generated by Docker)';
  rows.push({
    key: 'name',
    step: 1,
    label: 'Name',
    values: [nameDisplay],
    origin: containerName.trim() ? undefined : 'Docker will assign a name',
  });

  // — Ports —
  if (portInput.trim()) {
    rows.push({ key: 'ports', step: 2, label: 'Ports', values: [portInput.trim()] });
  } else if (previewedPorts && previewedPorts.length > 0) {
    const portLines = previewedPorts.map(
      (p) => `${p.hostPort}\u2192${p.containerPort}/${p.protocol}`
    );
    rows.push({
      key: 'ports',
      step: 2,
      label: 'Ports',
      values: portLines,
      origin: 'assigned by CDD',
    });
  } else {
    rows.push({
      key: 'ports',
      step: 2,
      label: 'Ports',
      values: ['CDD will pick a free port at creation'],
    });
  }

  // — Env —
  const envVars = (envInput || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  if (envVars.length > 0) {
    const envLines = envVars.map((v) => {
      const eqIdx = v.indexOf('=');
      if (eqIdx === -1) return v;
      const key = v.slice(0, eqIdx);
      const profile = imageProfiles[baseName];
      const isSecret =
        key.toUpperCase().includes('PASSWORD') ||
        key.toUpperCase().includes('SECRET') ||
        key.toUpperCase().includes('TOKEN') ||
        (profile?.requiredEnv || []).includes(key);
      return isSecret ? `${key}=\u2022\u2022\u2022\u2022\u2022\u2022` : v;
    });
    rows.push({ key: 'env', step: 3, label: 'Env', values: envLines });
  } else {
    rows.push({ key: 'env', step: 3, label: 'Env', values: ['(none)'] });
  }

  return rows;
}

/**
 * Detects host port conflicts against existing containers.
 *
 * @param {string} portInput - User's raw port input (e.g. "8080:80,5432:5432")
 * @param {Array<{ports: string[], name: string}>} containers
 * @returns {Array<{hostPort: string, takenBy: string}>}
 */
export function detectPortConflicts(portInput, containers) {
  if (!portInput?.trim()) return [];
  const conflicts = [];
  const pairs = portInput
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  for (const pair of pairs) {
    const [hostPort] = pair.split(':');
    if (!hostPort) continue;
    for (const container of containers) {
      if (container.ports?.includes(hostPort)) {
        conflicts.push({ hostPort, takenBy: container.name || container.id });
      }
    }
  }
  return conflicts;
}

/**
 * Builds warnings for the review step.
 * Receives pre-resolved external data to stay pure and testable.
 *
 * @param {Object} values - { imageName, containerName, portInput, envInput }
 * @param {Object} ctx
 * @param {Array} ctx.containers - Current container list
 * @param {boolean|null} ctx.imageIsLocal - null if unknown
 * @param {Object} ctx.imageProfiles
 * @returns {Warning[]}
 */
export function buildCreationWarnings(values, ctx) {
  const { imageName, containerName, portInput, envInput } = values;
  const { containers, imageIsLocal, imageProfiles } = ctx;
  const warnings = [];

  // Image not local
  if (imageIsLocal === false) {
    warnings.push({
      kind: 'image-pull',
      level: 'info',
      text: 'The image is not on your machine and will be pulled before creation.',
    });
  }

  // Port conflicts
  const portConflicts = detectPortConflicts(portInput, containers);
  for (const conflict of portConflicts) {
    warnings.push({
      kind: 'port-taken',
      level: 'warn',
      text: `Host port ${conflict.hostPort} is already used by "${conflict.takenBy}".`,
    });
  }

  // Name taken
  if (containerName?.trim()) {
    const nameTaken = containers.some(
      (c) => c.name === containerName.trim() || c.id === containerName.trim()
    );
    if (nameTaken) {
      warnings.push({
        kind: 'name-taken',
        level: 'block',
        text: `A container named "${containerName.trim()}" already exists.`,
      });
    }
  }

  // Missing required env vars
  const baseName = normalizeImageName(imageName);
  const profile = imageProfiles[baseName];
  if (profile?.requiredEnv?.length) {
    const presentKeys = (envInput || '')
      .split(',')
      .map((s) => s.split('=')[0].trim())
      .filter(Boolean);
    const missing = profile.requiredEnv.filter((k) => !presentKeys.includes(k));
    if (missing.length > 0) {
      warnings.push({
        kind: 'missing-env',
        level: 'warn',
        text: `Missing required env vars: ${missing.join(', ')}.`,
      });
    }
  }

  // Secrets in plain text
  const envVars = (envInput || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  for (const v of envVars) {
    const eqIdx = v.indexOf('=');
    if (eqIdx === -1) continue;
    const key = v.slice(0, eqIdx).toUpperCase();
    if (key.includes('PASSWORD') || key.includes('SECRET') || key.includes('TOKEN')) {
      warnings.push({
        kind: 'secret-plain',
        level: 'warn',
        text: `"${v.slice(0, eqIdx)}" contains a secret in plain text.`,
      });
    }
  }

  return warnings;
}
