import { normalizeImageName } from './imageNameUtils.js';
import { isSecretKey, findWeakSecrets } from './secrets.js';
import { hostPortsOf } from './portUtils.js';
import { parseEnvPairs } from './envInput.js';

/**
 * @typedef {Object} SummaryRow
 * @property {string} key     - 'image' | 'name' | 'ports' | 'env'
 * @property {number} step    - Step index to jump to when editing
 * @property {string} label   - Display label
 * @property {string[]} values - One or more value lines
 * @property {string} [origin] - Explanatory second line
 * @property {boolean} [changed] - True when CDD altered this row (TASK-8)
 */

/**
 * Which wizard field feeds which summary row. Used to translate a fix's
 * changedFields — which speak field names — into the rows the user sees.
 */
const ROW_OF_FIELD = {
  imageName: 'image',
  containerName: 'name',
  portInput: 'ports',
  envInput: 'env',
};

/** Shown in place of the mask for a secret that has no value. */
export const EMPTY_VALUE = '(empty)';

/**
 * @typedef {Object} Warning
 * @property {'image-pull'|'port-taken'|'name-taken'|'missing-env'|'secret-plain'} kind
 * @property {'info'|'warn'|'block'} level
 * @property {string} text
 */

/**
 * Builds the summary table from wizard values.
 * Pure: does not call Docker.
 *
 * @param {Object} values - { imageName, containerName, portInput, envInput }
 * @param {Object} ctx
 * @param {string} ctx.rawImageInput - What the user originally typed for the image
 * @param {Object} ctx.imageProfiles - Profile map
 * @param {Array} [ctx.previewedPorts] - Auto-assigned ports from preview, or null
 * @param {string[]} [ctx.changedFields] - Wizard fields CDD changed (TASK-8)
 * @param {boolean} [ctx.recreating] - True when the values were prefilled from a failed container
 * @returns {SummaryRow[]}
 */
export function buildCreationSummary(values, ctx) {
  const { imageName, containerName, portInput, envInput } = values;
  const {
    rawImageInput,
    imageProfiles,
    previewedPorts,
    changedFields = [],
    recreating = false,
  } = ctx;

  // The point of "recreate with the fix" is that the user can see what CDD
  // did before confirming it, so the touched rows are flagged rather than
  // silently different from the container that failed.
  const changedRows = new Set(
    changedFields.map((field) => ROW_OF_FIELD[field]).filter(Boolean)
  );
  const flag = (row) =>
    changedRows.has(row.key) ? { ...row, changed: true } : row;

  const rows = [];

  // — Image —
  const baseName = normalizeImageName(imageName);
  const imageValues = [imageName];
  let imageOrigin;
  if (rawImageInput && rawImageInput !== imageName) {
    imageOrigin = `you typed "${rawImageInput}"`;
  }
  rows.push({
    key: 'image',
    step: 0,
    label: 'Image',
    values: imageValues,
    origin: imageOrigin,
  });

  // — Name —
  const nameDisplay = containerName.trim() || '(auto-generated by Docker)';
  rows.push({
    key: 'name',
    step: 1,
    label: 'Name',
    values: [nameDisplay],
    origin: containerName.trim() ? undefined : 'Docker will assign a name',
  });

  // — Ports —
  if (portInput.trim()) {
    rows.push({
      key: 'ports',
      step: 2,
      label: 'Ports',
      values: [portInput.trim()],
    });
  } else if (previewedPorts && previewedPorts.length > 0) {
    const portLines = previewedPorts.map(
      (p) =>
        `${p.hostPort ?? '(no free host port)'}→${p.containerPort}/${
          p.protocol
        }`
    );
    rows.push({
      key: 'ports',
      step: 2,
      label: 'Ports',
      values: portLines,
      // A recreation reads like a copy of the original, so say when the
      // ports are new rather than carried over.
      origin: recreating
        ? 'assigned by CDD \u2014 the original published no ports'
        : 'assigned by CDD',
    });
  } else {
    rows.push({
      key: 'ports',
      step: 2,
      label: 'Ports',
      values: ['CDD will pick a free port at creation'],
    });
  }

  // — Env —
  const envPairs = parseEnvPairs(envInput);
  if (envPairs.length > 0) {
    const envLines = envPairs.map(({ key, value }) => {
      if (value === null) return key;
      if (!isSecretKey(key)) return `${key}=${value}`;
      // Nothing to hide in an empty value, and dots would claim otherwise.
      if (!value.trim()) return `${key}=${EMPTY_VALUE}`;
      return `${key}=\u2022\u2022\u2022\u2022\u2022\u2022`;
    });
    rows.push({ key: 'env', step: 3, label: 'Env', values: envLines });
  } else {
    rows.push({ key: 'env', step: 3, label: 'Env', values: ['(none)'] });
  }

  return rows.map(flag);
}

/**
 * Detects host port conflicts against existing containers.
 *
 * @param {string} portInput - User's raw port input (e.g. "8080:80,5432:5432")
 * @param {Array<{ports: string[], name: string}>} containers
 * @returns {Array<{hostPort: string, takenBy: string}>}
 */
export function detectPortConflicts(portInput, containers) {
  if (!portInput?.trim()) return [];
  const conflicts = [];
  const pairs = portInput
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  for (const pair of pairs) {
    const [hostPort] = pair.split(':');
    if (!hostPort) continue;
    for (const container of containers) {
      if (hostPortsOf(container).includes(hostPort)) {
        conflicts.push({ hostPort, takenBy: container.name || container.id });
      }
    }
  }
  return conflicts;
}

/**
 * Builds warnings for the review step.
 * Receives pre-resolved external data to stay pure and testable.
 *
 * @param {Object} values - { imageName, containerName, portInput, envInput }
 * @param {Object} ctx
 * @param {Array} ctx.containers - Current container list
 * @param {boolean|null} ctx.imageIsLocal - null if unknown
 * @param {Object} ctx.imageProfiles
 * @returns {Warning[]}
 */
export function buildCreationWarnings(values, ctx) {
  const { imageName, containerName, portInput, envInput } = values;
  const { containers, imageIsLocal, imageProfiles } = ctx;
  const warnings = [];

  // Image not local
  if (imageIsLocal === false) {
    warnings.push({
      kind: 'image-pull',
      level: 'info',
      text: 'The image is not on your machine and will be pulled before creation.',
    });
  }

  // Port conflicts
  const portConflicts = detectPortConflicts(portInput, containers);
  for (const conflict of portConflicts) {
    warnings.push({
      kind: 'port-taken',
      level: 'warn',
      text: `Host port ${conflict.hostPort} is already used by "${conflict.takenBy}".`,
    });
  }

  // Name taken
  if (containerName?.trim()) {
    const nameTaken = containers.some(
      (c) => c.name === containerName.trim() || c.id === containerName.trim()
    );
    if (nameTaken) {
      warnings.push({
        kind: 'name-taken',
        level: 'block',
        text: `A container named "${containerName.trim()}" already exists.`,
      });
    }
  }

  // Missing required env vars
  const baseName = normalizeImageName(imageName);
  const profile = imageProfiles[baseName];
  if (profile?.requiredEnv?.length) {
    const presentKeys = parseEnvPairs(envInput)
      .map((p) => p.key)
      .filter(Boolean);
    const missing = profile.requiredEnv.filter((k) => !presentKeys.includes(k));
    if (missing.length > 0) {
      warnings.push({
        kind: 'missing-env',
        level: 'warn',
        text: `Missing required env vars: ${missing.join(', ')}.`,
      });
    }
  }

  // Required vars that are present but carry no value. Distinct from "missing":
  // the key is there, and the container will start, fail, and say the very
  // thing CDD just diagnosed. TASK-8's password fix lands here on purpose —
  // CDD cannot invent a password — so the review has to say so out loud.
  if (profile?.requiredEnv?.length) {
    // Named given, not values: `values` is the wizard-values parameter and
    // shadowing it here made the two impossible to tell apart.
    const given = new Map(
      parseEnvPairs(envInput).map(({ key, value }) => [key, value])
    );
    const empty = profile.requiredEnv.filter((k) => {
      if (!given.has(k)) return false;
      const v = given.get(k);
      return v !== null && v.trim() === '';
    });
    if (empty.length > 0) {
      warnings.push({
        kind: 'missing-env',
        level: 'warn',
        text: `Required env var${empty.length === 1 ? '' : 's'} set but empty: ${empty.join(', ')}. Fill ${empty.length === 1 ? 'it' : 'them'} in before creating — the container will fail without ${empty.length === 1 ? 'a value' : 'values'}.`,
      });
    }
  }

  // Secrets in plain text
  for (const { key, value } of parseEnvPairs(envInput)) {
    if (value === null) continue;
    // No value, nothing in plain text: the empty-value warning covers it.
    if (isSecretKey(key) && value.trim()) {
      warnings.push({
        kind: 'secret-plain',
        level: 'warn',
        text: `"${key}" contains a secret in plain text.`,
      });
    }
  }

  // Weak secrets
  const weakSecrets = findWeakSecrets(envInput);
  for (const { key, reason } of weakSecrets) {
    const reasonText =
      reason === 'example'
        ? 'uses an example value'
        : reason === 'short'
          ? 'is too short'
          : 'uses a common password';
    warnings.push({
      kind: 'secret-weak',
      level: 'warn',
      text: `"${key}" ${reasonText}. Consider using [Ctrl+G] to generate a strong password.`,
    });
  }

  return warnings;
}
